simply enable V4 signatures
Fails against Minio:

[cargohold] E, request=N/A, HttpExceptionRequest Request
    {   host                 = "localhost"
        port                 = 4570
        secure               = False
        requestHeaders       = [("Date","Fri, 26 Jun 2020 16:01:56 GMT"),("Content-Type","application/text"),("Authorization","<REDACTED>"),("X-Amz-Content-Sha256","UNSIGNED-PAYLOAD"),("X-Amz-Date","20200626T160156Z"),("x-amz-meta-token","_1lFtT49aeFXeddM2zXTQg=="),("x-amz-meta-user","c49b2898-16bd-401b-9e08-ab799b2016bc"),("Expect","100-continue")]   path                 = "/dummy-bucket/v3/persistent/b5f1f0f8-c4b9-42ec-86b0-da7f34ba0296"
        queryString          = ""
        method               = "PUT"
        proxy                = Nothing
        rawBody              = False
        redirectCount        = 10
        responseTimeout      = ResponseTimeoutDefault
        requestVersion       = HTTP/1.1
    }
ResponseTimeout

Response {responseStatus = Status {statusCode = 500, statusMessage = "Internal Server Error"}, responseVersion = HTTP/1.1, responseHeaders = [("Transfer-Encoding","chunked"),("Date","Fri, 26 Jun 2020 16:02:06 GMT"),("Server","Warp/3.3.5"),("Content-Type","application/json")], responseBody = Just "{\"code\":500,\"message\":\"Server Error\",\"label\":\"server-error\"}", responseCookieJar = CJ {expose = []}, responseClose' = ResponseClose}

Fails against S3:

[cargohold] E, request=N/A, S3Error {s3StatusCode = Status {statusCode = 403, statusMessage = "Forbidden"}, s3ErrorCode = "AccessDenied", s3ErrorMessage = "There were headers present in the request which were not signed", s3ErrorResource = Nothing, s3ErrorHostId = Just "RfJE6ek9+5IY6E8n6ogxoqukJ8Y2/Q0HDiPohE7wyHkNwHm0KBxzwvj+HoZc27DSZUT69AGSduc=", s3ErrorAccessKeyId = Nothing, s3ErrorStringToSign = Nothing, s3ErrorBucket = Nothing, s3ErrorEndpointRaw = Nothing, s3ErrorEndpoint = Nothing}

Response {responseStatus = Status {statusCode = 500, statusMessage = "Internal Server Error"}, responseVersion = HTTP/1.1, responseHeaders = [("Transfer-Encoding","chunked"),("Date","Fri, 26 Jun 2020 16:05:16 GMT"),("Server","Warp/3.3.5"),("Content-Type","application/json")], responseBody = Just "{\"code\":500,\"message\":\"\\u001f\239\191\189\\u0008\\u0000\\u0000\\u0000\\u0000\\u0000\\u0004\\u0003\239\191\189VJ\239\191\189OIU\239\191\189\&250\239\191\189Q\239\191\189M-.NL\\u0007\239\191\189\239\191\189\239\191\189S\239\191\189\239\191\189R\239\191\189\\u0014\\\\\239\191\189\239\191\189\239\191\189\239\191\189\239\191\189\239\191\189t\239\191\189r\\u0012\239\191\189Rs\239\191\189\239\191\189\239\191\189`q\239\191\189T\239\191\189\239\191\189R-\\u0000v,\239\191\189\239\191\189=\\u0000\\u0000\\u0000\",\"label\":\"server-error\"}", responseCookieJar = CJ {expose = []}, responseClose' = ResponseClose}

Exception: HttpExceptionRequest Request
    {   host                 = "s3-eu-west-1.amazonaws.com"
        port                 = 443
        secure               = True
        requestHeaders       = []
        path                 = "/temporary-cargohold-test-mheinzel/v3/persistent/8e27d2c9-af36-48fc-ab09-4497189951fd"
        queryString          = "?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=AKIARLM3WMDQYUDWSKUY%2F20200626%2Feu-west-1%2Fs3%2Faws4_request&X-Amz-Date=20200626T160517Z&X-Amz-Expires=300&X-Amz-SignedHeaders=host%3Bx-amz-content-sha256%3Bx-amz-date&X-Amz-Signature=00ab64e6f67ad4070f33cc5fdbb20ead035572ecd014885e623df9cbacba9202"
        method               = "GET"
        proxy                = Nothing
        rawBody              = False
        redirectCount        = 10
        responseTimeout      = ResponseTimeoutDefault
        requestVersion       = HTTP/1.1
    }
    (StatusCodeException (Response {responseStatus = Status {statusCode = 403, statusMessage = "Forbidden"}, responseVersion = HTTP/1.1, responseHeaders = [("x-amz-request-id","B6316150E26A04A1"),("x-amz-id-2","pdc5rlQpkkUnsZ9pkAlxS9n6qHhhbggP4EzPnnsflO8UT7emSDQS8sZ460GlQGoiVxtyWv7OYhw="),("Content-Type","application/xml"),("Transfer-Encoding","chunked"),("Date","Fri, 26 Jun 2020 16:05:18 GMT"),("Server","AmazonS3")], responseBody = (), responseCookieJar = CJ {expose = []}, responseClose' = ResponseClose}) "<?xml version=\"1.0\" encoding=\"UTF-8\"?>\n<Error><Code>SignatureDoesNotMatch</Code><Message>The request signature we calculated does not match the signature you provided. Check your key and signing method.</Message><AWSAccessKeyId>AKIARLM3WMDQYUDWSKUY</AWSAccessKeyId><StringToSign>AWS4-HMAC-SHA256\n20200626T160517Z\n20200626/eu-west-1/s3/aws4_request\n38e7b83e078fc8edd59986a52645ceeef4719538a2ca8d3655166beafef11cf8</StringToSign><SignatureProvided>00ab64e6f67ad4070f33cc5fdbb20ead035572ecd014885e623df9cbacba9202</SignatureProvided><StringToSignBytes>41 57 53 34 2d 48 4d 41 43 2d 53 48 41 32 35 36 0a 32 30 32 30 30 36 32 36 54 31 36 30 35 31 37 5a 0a 32 30 32 30 30 36 32 36 2f 65 75 2d 77 65 73 74 2d 31 2f 73 33 2f 61 77 73 34 5f 72 65 71 75 65 73 74 0a 33 38 65 37 62 38 33 65 30 37 38 66 63 38 65 64 64 35 39 39 38 36 61 35 32 36 34 35 63 65 65 65 66 34 37 31 39 35 33 38 61 32 63 61 38 64 33 36 35 35 31 36 36 62 65 61 66 65 66 31 31 63 66 38</StringToSignBytes><CanonicalRequest>GET\n/temporary-cargohold-test-mheinzel/v3/persistent/8e27d2c9-af36-48fc-ab09-4497189951fd\nX-Amz-Algorithm=AWS4-HMAC-SHA256&amp;X-Amz-Credential=AKIARLM3WMDQYUDWSKUY%2F20200626%2Feu-west-1%2Fs3%2Faws4_request&amp;X-Amz-Date=20200626T160517Z&amp;X-Amz-Expires=300&amp;X-Amz-SignedHeaders=host%3Bx-amz-content-sha256%3Bx-amz-date\nhost:s3-eu-west-1.amazonaws.com\nx-amz-content-sha256:\nx-amz-date:\n\nhost;x-amz-content-sha256;x-amz-date\nUNSIGNED-PAYLOAD</CanonicalRequest><CanonicalRequestBytes>47 45 54 0a 2f 74 65 6d 70 6f 72 61 72 79 2d 63 61 72 67 6f 68 6f 6c 64 2d 74 65 73 74 2d 6d 68 65 69 6e 7a 65 6c 2f 76 33 2f 70 65 72 73 69 73 74 65 6e 74 2f 38 65 32 37 64 32 63 39 2d 61 66 33 36 2d 34 38 66 63 2d 61 62 30 39 2d 34 34 39 37 31 38 39 39 35 31 66 64 0a 58 2d 41 6d 7a 2d 41 6c 67 6f 72 69 74 68 6d 3d 41 57 53 34 2d 48 4d 41 43 2d 53 48 41 32 35 36 26 58 2d 41 6d 7a 2d 43 72 65 64 65 6e 74 69 61 6c 3d 41 4b 49 41 52 4c 4d 33 57 4d 44 51 59 55 44 57 53 4b 55 59 25 32 46 32 30 32 30 30 36 32 36 25 32 46 65 75 2d 77 65 73 74 2d 31 25 32 46 73 33 25 32 46 61 77 73 34 5f 72 65 71 75 65 73 74 26 58 2d 41 6d 7a 2d 44 61 74 65 3d 32 30 32 30 30 36 32 36 54 31 36 30 35 31 37 5a 26 58 2d 41 6d 7a 2d 45 78 70 69 72 65 73 3d 33 30 30 26 58 2d 41 6d 7a 2d 53 69 67 6e 65 64 48 65 61 64 65 72 73 3d 68 6f 73 74 25 33 42 78 2d 61 6d 7a 2d 63 6f 6e 74 65 6e 74 2d 73 68 61 32 35 36 25 33 42 78 2d 61 6d 7a 2d 64 61 74 65 0a 68 6f 73 74 3a 73 33 2d 65 75 2d 77 65 73 74 2d 31 2e 61 6d 61 7a 6f 6e 61 77 73 2e 63 6f 6d 0a 78 2d 61 6d 7a 2d 63 6f 6e 74 65 6e 74 2d 73 68 61 32 35 36 3a 0a 78 2d 61 6d 7a 2d 64 61 74 65 3a 0a 0a 68 6f 73 74 3b 78 2d 61 6d 7a 2d 63 6f 6e 74 65 6e 74 2d 73 68 61 32 35 36 3b 78 2d 61 6d 7a 2d 64 61 74 65 0a 55 4e 53 49 47 4e 45 44 2d 50 41 59 4c 4f 41 44</CanonicalRequestBytes><RequestId>B6316150E26A04A1</RequestId><HostId>pdc5rlQpkkUnsZ9pkAlxS9n6qHhhbggP4EzPnnsflO8UT7emSDQS8sZ460GlQGoiVxtyWv7OYhw=</HostId></Error>")